version: "beta-1"
name: "energy_monitoring"

services:
  mysql:
    image: 'mysql:latest'
    container_name: 'monitoring-sys-database'
    restart: always
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

  mosquitto:
    image: 'eclipse-mosquitto:latest'
    container_name: 'mosquitto-mqtt'
    hostname: 'mosquitto-mqtt'
    volumes:
      - type: bind
        source: ./init-scripts/mosquitto/mosquitto.conf
        target: /mosquitto/config/mosquitto.conf
    ports:
      - "1883:1883"
    expose:
      - "1883"