services:
  mysql:
    image: 'mysql:latest'
    container_name: 'monitoring-sys-database'
    restart: always
    environment:
      - 'MYSQL_DATABASE=mydatabase'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
      - '33060:33060'
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d