spring.application.name=eams

# Set port to 2563 to avoid port config, bind to 0.0.0.0 enabling listen to all network interfaces
server.address=0.0.0.0
server.port=2563

# Config datasource (For debug only)
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:127.0.0.1}:3306/energy_management
#spring.datasource.username=root
#spring.datasource.password=verysecret
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# For packaging only
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Config JPA/Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Config view engine
spring.mvc.view.prefix=/WEB-INF/view/
spring.mvc.view.suffix=.jsp

spring.jpa.open-in-view=false
hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform